### PR TITLE
Add in different map extent/fontsizes depending on global or regional

### LINKED ISSUE #45: Add Xiaoyan's regional spatial plot to repository
@xyzemc created a nice, zoomed in map covering N America that would be useful for RRFS. This needs to be added to plot_spatial, etc. I think with a regional=True argument.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Closes #45 (I think)

Adds a new function to return different dictionaries depending on global or regional, these dictionaries set things like figure size, map extent, font sizes, etc.

Then the plot_spatial routines use this new function combined with the dictionary when generating the figures. A future PR should probably use this dictionary in the binned spatial plot also.

### CODE REVIEW

**Review by xyzemc — COMMENTED** [review]
Everything looks good.

**Comment by CoryMartin-NOAA** [comment]
thanks @xyzemc , could you 'approve' the PR then?

**Review by xyzemc — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa I will wait for you to review/merge if you approve

**Review by kevindougherty-noaa — APPROVED** [review]
Looks good to me. I will approve and merge.

**Pull request merged**
