### PR TITLE
Feature/pygsi su

### PR DESCRIPTION
**Pull request by XiujuanSu-NOAA**
Thanks, I leave high_idx to Ed to fix it.

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@XiujuanSu-NOAA this pull request is attempting to merge in things that were already committed in the previous pull request. Did you merge in 'main' to your branch? This has 4 commits in it but I suspect you only want the most recent one included.

**Comment by XiujuanSu-NOAA** [comment]
I will check what I have done.  Thanks

**Comment by XiujuanSu-NOAA** [comment]
Hi Cory

What I did was to checkout the latest main to get  feature/PYGSI_su branch,
then work from there to commit what I have done(fixing some lines as
mentioned in the issues).  I don't know why I try to commit previous
changes.  Can you tell me what I should do?  Thank you very much.

Su

**Comment by CoryMartin-NOAA** [comment]
@XiujuanSu-NOAA I think what you need to do is the following:
```
git checkout main
git pull
git checkout feature/PYGSI_su
git merge main
git push
```
See if that helps.

In general, it is not good practice to use the same branch name. For this change, I would suggest a branch name like `bugfix/idx` as it is a bug fix and not a new feature.

**Comment by XiujuanSu-NOAA** [comment]
Hi Cory
  Thanks
I did what you told me  from your last email,  I saw the message:Already up
to date. after I typed git pull.

What's next?

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by XiujuanSu-NOAA** [comment]
Thank you very much for your help.  I learn a lot from you .

**Review by EdwardSafford-NOAA — APPROVED** [review]
Works for me.  Thanks Su.

**Pull request merged**
